md5_to_dsma: Fix % error on Python 3.14
With python 3.14.4 writing % in the string causes an error. I've added a
second one to fix the issue.

Here the error I got previously:

```
python3 md5_to_dsma.py --model Robot.md5mesh \
               --name robot \
               --output out_folder \
               --texture 128 128 \
               --anim Wave.md5anim Walk.md5anim Bow.md5anim
md5_to_dsma v0.1.1
Copyright (c) 2022-2024 Antonio Niño Díaz <antonio_nd@outlook.com>
All rights reserved

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.14/3.14.4/Frameworks/Python.framework/Versions/3.14/lib/python3.14/argparse.py", line 1748, in _check_help
    formatter._expand_help(action)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.14/3.14.4/Frameworks/Python.framework/Versions/3.14/lib/python3.14/argparse.py", line 676, in _expand_help
    return help_string % params
           ~~~~~~~~~~~~^~~~~~~~
ValueError: unsupported format character ',' (0x2c) at index 89

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mac/Downloads/dsma-library/tools/md5_to_dsma.py", line 811, in <module>
    parser.add_argument("--skip-frames", required=False,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        default=0, type=int,
                        ^^^^^^^^^^^^^^^^^^^^
                        help="number of frames to skip in an animation (0 = export all, 1 = export half, 2 = export 33%, etc)")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.14/3.14.4/Frameworks/Python.framework/Versions/3.14/lib/python3.14/argparse.py", line 1562, in add_argument
    self._check_help(action)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.14/3.14.4/Frameworks/Python.framework/Versions/3.14/lib/python3.14/argparse.py", line 1750, in _check_help
    raise ValueError('badly formed help string') from exc
ValueError: badly formed help string
```